export enum ProductCategory {
    HOME_DECOR = "HOME_DECOR",
    FASHION = "FASHION",
    FURNITURE = "FURNITURE",
    ACCESSORIES = "ACCESSORIES",
    TOYS = "TOYS",
    GARDEN = "GARDEN",
    ART = "ART",
    KITCHENWARE = "KITCHENWARE",
}
